### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by diogotfernandes** [kiteria/ansible#1]
- [ ] Verificar como é feita a autenticação inicial, numa máquina nova. (user+pw???)
- [x] Criar hash de password de novo utilizador
```yaml
ansible all -i localhost, -m debug -a "msg={{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}" 
```
[Creating a new user and password with Ansible](https://stackoverflow.com/questions/19292899/creating-a-new-user-and-password-with-ansible)
[How do I generate encrypted passwords for the user module?
](https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module)
- [x] Remover utilizador por omissão, na instalação de uma nova máquina
- [ ] Perceber melhor o fluxo da instalação de uma nova máquina (qual é a melhor ordem???)
- [x] Host key checking
[How to set host_key_checking=false in ansible inventory file?](https://stackoverflow.com/questions/23074412/how-to-set-host-key-checking-false-in-ansible-inventory-file)
* Ficheiro de hosts:
```yaml
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
```

**Comment by diogotfernandes** [comment]
- [x] Como adicionar/remover/editar entradas de DNS?
`manualmente ou com o nsupdate!`

**Comment by diogotfernandes** [comment]
Tracking progress through a loop with [`index_var`](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#tracking-progress-through-a-loop-with-index-var)
